GET http://localhost:5000/miniaturas

###
GET http://localhost:5000/miniaturas?marca_id=2

###
GET http://localhost:5000/miniaturas/1

###
POST http://localhost:5000/miniaturas
Content-Type: application/json

{
  "modelo": "Chevrolet Corvette C8",
  "escala": "1:18",
  "preco": 350.00,
  "marca_id": 2
}

###
PUT http://localhost:5000/miniaturas/2
Content-Type: application/json

{
  "modelo": "Dodge Charger R/T",
  "escala": "1:24",
  "preco": 210.00,
  "marca_id": 2
}

###
DELETE http://localhost:5000/miniaturas/2
